[package]
name = "rknputop"
version = "0.1.0"
edition = "2021"
description = "NPU/CPU/Memory/Thermal monitoring tool for Rockchip NPUs"
license = "GPL-3.0"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
regex = "1.10"
